//get
export const GET_DISHES_START = "GET_DISHES_START";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_DISHES_FAIL = "GET_DISHES_FAIL";

export const GET_PROFILE_REVIEWS_START = "GET_PROFILE_REVIEWS_START";
export const GET_PROFILE_REVIEWS_SUCCESS = "GET_PROFILE_REVIEWS_SUCCESS";
export const GET_PROFILE_REVIEWS_FAILURE = "GET_PROFILE_REVIEWS_FAILURE";

//create
export const CREATE_DISH_START = "CREATE_DISH_START";
export const CREATE_DISH_SUCCESS = "CREATE_DISH_SUCCESS";
export const CREATE_DISH_FAIL = "CREATE_DISH_FAIL";

export const SET_IMAGE = "SET_IMAGE";


//filtering
export const FILTER_DISHES = 'FILTER_DISHES'