//get restaurants
export const GET_RESTAURANT_START = "GET_RESTAURANT_START";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL";

//create restaurant
export const CREATE_RESTAURANT_START = "CREATE_RESTAURANT_START";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";

export const SET_IMAGE = "SET_IMAGE";

//delete restaurant

export const DELETE_RESTAURANT_START = 'DELETE_RESTAURANT_START';
export const DELETE_RESTAURANT_SUCCESS  = 'DELETE_RESTAURANT_SUCCESS';
export const DELETE_RESTAURANT_FAILURE = 'DELETE_RESTAURANT_FAILURE';

//update restaurant

export const UPDATE_RESTAURANT_START = 'UPDATE_RESTAURANT_START';
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS';
export const UPDATE_RESTAURANT_FAILURE = 'UPDATE_RESTAURANT_FAILURE';

//filter
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS'