//get restaurants
export const GET_RESTAURANT_START = "GET_RESTAURANT_START";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL";

//create restaurant
export const CREATE_RESTAURANT_START = "CREATE_RESTAURANT_START";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";

export const SET_IMAGE = "SET_IMAGE";